name: ci

on:
  push:
  pull_request:

jobs:
  debian:
    runs-on: ubuntu-latest
    container: debian:stable-slim
    steps:
      - uses: actions/checkout@v4
      - run: ./dependencies.sh
      - run: make
      - run: make test
      - run: make deb
      - run: dpkg -i build/*.deb
      - run: wgwatch --help
      - uses: actions/upload-artifact@v4
        with:
          name: wgwatch-deb
          path: build/*.deb

  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v4
      - run: ./dependencies.sh
      - run: make
      - run: make test
      - run: make rpm
      - run: dnf install -y ./build/*.rpm
      - run: wgwatch --help
      - uses: actions/upload-artifact@v4
        with:
          name: wgwatch-rpm
          path: build/*.rpm

  nix-shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop --command bash -c 'make && make test'

  nix-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#default
      - run: ./result/bin/wgwatch --help
